# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: BuildSolution
  displayName: Build solution
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
  - job: Test
    displayName: Test
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/*Tests.csproj'
- stage: BuildDockerImageAPI
  dependsOn: BuildSolution
  displayName: Build and push API Docker image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'PaymentGateway'
        repository: 'paymentgateway-api'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/PaymentGateway.Api/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
- stage: BuildDockerImageMerchant
  dependsOn: BuildSolution
  displayName: Build and push merchant Docker image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'PaymentGateway'
        repository: 'paymentgateway-merchant'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/PaymentGateway.Merchant/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
- stage: BuildDockerImageBank
  dependsOn: BuildSolution
  displayName: Build and push bank Docker image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'PaymentGateway'
        repository: 'paymentgateway-bank'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/PaymentGateway.Bank/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
